package com.judahben149.emvsync.utils.isoUtils

object IsoResponseUtils {

    fun formatIsoResponse(responseCode: String): String? {
        val responseMessageMap: MutableMap<String, String> = HashMap()

        responseMessageMap["00"] = "Transaction Approved"
        responseMessageMap["01"] = "Refer to card issuer"
        responseMessageMap["02"] = "Refer to card issuer, special condition"
        responseMessageMap["03"] = "Invalid merchant"
        responseMessageMap["04"] = "Pick-up card"
        responseMessageMap["05"] = "Do not honor"
        responseMessageMap["06"] = "Error"
        responseMessageMap["07"] = "Pick-up card, special condition"
        responseMessageMap["08"] = "Honor with identification"
        responseMessageMap["09"] = "Request in progress"
        responseMessageMap["10"] = "Contact Issuing Bank"
        responseMessageMap["11"] = "Contact Issuing Bank"
        responseMessageMap["12"] = "Invalid transaction"
        responseMessageMap["13"] = "Invalid amount"
        responseMessageMap["14"] = "Invalid card number"
        responseMessageMap["15"] = "No such issuer"
        responseMessageMap["16"] = "Contact Issuing Bank"
        responseMessageMap["17"] = "Customer cancellation"
        responseMessageMap["18"] = "Customer dispute"
        responseMessageMap["19"] = "Re-enter transaction"
        responseMessageMap["20"] = "Invalid response"
        responseMessageMap["21"] = "No action taken"
        responseMessageMap["22"] = "Suspected malfunction"
        responseMessageMap["23"] = "Unacceptable transaction fee"
        responseMessageMap["24"] = "File update not supported"
        responseMessageMap["25"] = "Unable to locate record"
        responseMessageMap["26"] = "Duplicate record"
        responseMessageMap["27"] = "File update field edit error"
        responseMessageMap["28"] = "File update file locked"
        responseMessageMap["29"] = "File update failed"
        responseMessageMap["30"] = "Format error"
        responseMessageMap["31"] = "Bank not supported"
        responseMessageMap["32"] = "Completed partially"
        responseMessageMap["33"] = "Expired card, pick-up"
        responseMessageMap["34"] = "Suspected fraud, pick-up"
        responseMessageMap["35"] = "Contact acquirer, pick-up"
        responseMessageMap["36"] = "Restricted card, pick-up"
        responseMessageMap["37"] = "Call acquirer security, pick-up"
        responseMessageMap["38"] = "PIN tries exceeded, pick-up"
        responseMessageMap["39"] = "No credit account"
        responseMessageMap["40"] = "Function not supported"
        responseMessageMap["41"] = "Lost card, pick-up"
        responseMessageMap["42"] = "No universal account"
        responseMessageMap["43"] = "Stolen card, pick-up"
        responseMessageMap["44"] = "No investment account"
        responseMessageMap["45"] = "Account closed"
        responseMessageMap["46"] = "Identification required"
        responseMessageMap["47"] = "Identification cross-check required"
        responseMessageMap["51"] = "Not sufficient funds"
        responseMessageMap["52"] = "No check account"
        responseMessageMap["53"] = "No savings account"
        responseMessageMap["54"] = "Expired card"
        responseMessageMap["55"] = "Incorrect PIN"
        responseMessageMap["56"] = "No card record"
        responseMessageMap["57"] = "Transaction not permitted to cardholder"
        responseMessageMap["58"] = "Transaction not permitted on terminal"
        responseMessageMap["59"] = "Suspected fraud"
        responseMessageMap["60"] = "Contact acquirer"
        responseMessageMap["61"] = "Exceeds withdrawal limit"
        responseMessageMap["62"] = "Restricted card"
        responseMessageMap["63"] = "Security violation"
        responseMessageMap["64"] = "Original amount incorrect"
        responseMessageMap["65"] = "Exceeds withdrawal frequency"
        responseMessageMap["66"] = "Call acquirer security"
        responseMessageMap["67"] = "Hard capture"
        responseMessageMap["68"] = "Response received too late"
        responseMessageMap["69"] = "Advice received too late"
        responseMessageMap["75"] = "PIN Tries Exceeded"
        responseMessageMap["80"] = "Visa transactions:credit issuer unavailable"
        responseMessageMap["81"] = "PIN cryptographic error found"
        responseMessageMap["82"] = "Negative CAM,dCVV,iCVV,orCVV results"
        responseMessageMap["83"] = "Unable to verify PIN"
        responseMessageMap["90"] = "Cut-off in progress"
        responseMessageMap["91"] = "Issuer or switch inoperative"
        responseMessageMap["92"] = "Routing error"
        responseMessageMap["93"] = "Violation of law"
        responseMessageMap["94"] = "Duplicate transaction"
        responseMessageMap["95"] = "Reconcile error"
        responseMessageMap["96"] = "System malfunction"
        responseMessageMap["98"] = "Exceeds cash limit"
        responseMessageMap["N0"] = "Force STIP"
        responseMessageMap["N3"] = "Cash service not available"
        responseMessageMap["N4"] = "Cashback request exceeds issuer limit"
        responseMessageMap["N7"] = "Decline for CVV2 failure"
        responseMessageMap["P2"] = "Invalid biller information"
        responseMessageMap["P5"] = "PIN change/unblock request declined"
        responseMessageMap["P6"] = "Unsafe PIN"
        responseMessageMap["Q1"] = "Card authentication failed"
        responseMessageMap["R0"] = "Stop payment order"
        responseMessageMap["R1"] = "Revocation of authorization order"
        responseMessageMap["R3"] = "Revocation of all authorizations order"
        responseMessageMap["XA"] = "Forward to issuer"
        responseMessageMap["XD"] = "Forward to issuer"
        responseMessageMap["Z3"] = "Unable to go online"
        responseMessageMap["-1"] = "Reversed"

        return responseMessageMap[responseCode]
    }
}